In [1]:
# 📁 01. 파일 불러오기

## ✅ 로컬에서 불러오기(csv/xlsx)
- csv
- xlsx

## ✅ 웹에서 불러오기(csv/xlsx)
- csv
- xlsx

## ✅ 헤더가 없는 경우 
- header = None
- header.columns = ['col1','col2', ... ]

SyntaxError: cannot assign to expression here. Maybe you meant '==' instead of '='? (753585126.py, line 8)

In [4]:
import pandas as pd

# 1.1 로컬_csv
file_path = "/Users/jangsohyun/Desktop/Introduction_to_AI/iris_data.csv"
df = pd.read_csv(file_path)

# 데이터프레임 확인
df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [7]:
import pandas as pd

# 1.2 로컬_xlsx
file_path = "/Users/jangsohyun/Desktop/Introduction_to_AI/iris_data.xlsx"
df = pd.read_excel(file_path)

# 데이터프레임 확인
df.head()

   5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

In [8]:
import pandas as pd

# 2.1 웹_csv
file_path = "https://raw.githubusercontent.com/MyungKyuYi/AI-class/refs/heads/main/diabetes.csv"
df = pd.read_csv(file_path)

# 데이터프레임 확인
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [13]:
import pandas as pd

# 2.2 웹_xlsx
file_path = "https://github.com/MyungKyuYi/AI-class/raw/refs/heads/main/combined_dataset-1.xlsx"
df = pd.read_excel(file_path)

# 데이터프레임 확인
df.head()

,Num.,subject_ID,Sex(M/F),Age(year),Height(cm),Weight(kg),Systolic Blood Pressure(mmHg),Diastolic Blood Pressure(mmHg),Heart Rate(b/m),BMI(kg/m^2),...,2091,2092,2093,2094,2095,2096,2097,2098,2099,2100
0,1,2,Female,45,152,63,161,89,97,27.268006,...,1766,1766,1766,1833,1833,1827,1827,1827,1754,1754
1,1,2,Female,45,152,63,161,89,97,27.268006,...,1985,1985,2026,2026,2026,1977,1977,1997,1997,1997
2,1,2,Female,45,152,63,161,89,97,27.268006,...,1942,1900,1900,1938,1938,1938,1924,1924,1929,1929
3,2,3,Female,50,157,50,160,93,76,20.284799,...,2073,2072,2072,2072,2051,2051,2036,2036,2036,2045
4,2,3,Female,50,157,50,160,93,76,20.284799,...,2021,2010,2010,2010,2001,2001,2003,2003,2003,1989

In [20]:
import pandas as pd

## header=None -> 파일에 헤더가 없는 상태이므로 첫 번째 행이 컬럼명이 되지 않도록 설정
df = pd.read_csv("/Users/jangsohyun/Desktop/Introduction_to_AI/car_evaluation.csv", header=None)
df.columns = ['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety', 'output']

print(df.columns)
print(df.head())

Index(['price', 'maint', 'doors', 'persons', 'lug_capacity', 'safety',
       'output'],
      dtype='object')
   price  maint doors persons lug_capacity safety output
0  vhigh  vhigh     2       2        small    low  unacc
1  vhigh  vhigh     2       2        small    med  unacc
2  vhigh  vhigh     2       2        small   high  unacc
3  vhigh  vhigh     2       2          med    low  unacc
4  vhigh  vhigh     2       2          med    med  unacc